# Generated by Django 5.2.7 on 2025-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='agent_phase',
            field=models.CharField(choices=[('analyze', 'Analisi iniziale'), ('interview', 'Raccolta informazioni'), ('refine', 'Raffinamento'), ('validate', 'Validazione'), ('complete', 'Completato')], default='analyze', help_text='Fase corrente del sistema agenti', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='collected_info',
            field=models.JSONField(blank=True, default=dict, help_text='Informazioni raccolte durante il dialogo (obiettivo, contesto, vincoli, formato output, etc.)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='identified_issues',
            field=models.JSONField(blank=True, default=list, help_text='Lista di problemi identificati nel prompt iniziale'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='iteration_count',
            field=models.IntegerField(default=0, help_text='Numero di iterazioni di raffinamento'),
        ),
    ]
