# Generated by Django 5.2.7 on 2025-10-26 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatsession_agent_phase_chatsession_collected_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Punteggio di confidence (0-100) sulla completezza delle informazioni raccolte', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
