# Generated by Django 5.2.7 on 2025-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chatsession_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='agent_phase',
            field=models.CharField(choices=[('analyze', 'Analisi iniziale'), ('interview', 'Raccolta informazioni'), ('data_collection', 'Raccolta dati'), ('refine', 'Raffinamento'), ('validate', 'Validazione'), ('complete', 'Completato')], default='analyze', help_text='Fase corrente del sistema agenti', max_length=50),
        ),
    ]
