# Generated by Django 5.2.7 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_chatsession_agent_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificativo del tool (es: web_search, code_interpreter)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Nome visualizzato nell'admin (es: Web Search, Code Interpreter)", max_length=200)),
                ('description', models.TextField(help_text='Descrizione delle funzionalità del tool')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('universal', 'Universale')], default='universal', help_text='Provider che supporta questo tool', max_length=100)),
                ('tool_type', models.CharField(help_text="Tipo di tool per l'API (es: 'web_search', 'code_interpreter', 'file_search')", max_length=100)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text="Configurazione specifica del tool in formato JSON. Es: {'type': 'web_search'} per OpenAI")),
                ('is_active', models.BooleanField(default=True, help_text="Tool attivo e disponibile per l'uso")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tool abilitati per questa configurazione (es: web search, code interpreter)', related_name='configurations', to='home.tool'),
        ),
    ]
